services:
  - type: web
    name: streetaffiliater-codex-web
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webhook_codex_receiver:app --host 0.0.0.0 --port $PORT
